// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessageToChat(arg1) {
  return window['go']['chat']['ChatCollection']['AddMessageToChat'](arg1);
}

export function GetRecentChats() {
  return window['go']['chat']['ChatCollection']['GetRecentChats']();
}
