// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function AddMessageToChat(arg1:chat.Message):void;

export function GetRecentChats():Promise<Array<chat.RecentChat>>;
