// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChatById(arg1) {
  return window['go']['ipc']['Channel']['GetChatById'](arg1);
}

export function GetRecentChats() {
  return window['go']['ipc']['Channel']['GetRecentChats']();
}

export function GetUserId() {
  return window['go']['ipc']['Channel']['GetUserId']();
}

export function GetUserPreferences() {
  return window['go']['ipc']['Channel']['GetUserPreferences']();
}

export function SendMessage(arg1) {
  return window['go']['ipc']['Channel']['SendMessage'](arg1);
}
