// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ipc} from '../models';

export function GetRecentChats():Promise<Array<ipc.RecentChat>>;

export function SendMessage(arg1:ipc.SendMessageRequest):Promise<ipc.SendMessageRequest>;
