// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserId() {
  return window['go']['main']['App']['GetUserId']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function GetChatById(arg1) {
  return window['go']['main']['App']['GetChatById'](arg1);
}

export function GetRecentChats() {
  return window['go']['main']['App']['GetRecentChats']();
}
